name: Feature Request
description: 機能追加の提案
title: "[Feat] <やりたいこと>"
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
      description: ユースケース/背景
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 提案内容
      description: 具体的な動作・UI・API など
      placeholder: 例) 新しいCLIオプション `--dry-run` を追加
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 代替案/妥協案
  - type: checkboxes
    id: scope
    attributes:
      label: 影響範囲
      options:
        - label: 破壊的変更の可能性がある
        - label: ドキュメント更新が必要
        - label: テスト追加が必要
